require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SupplementPlansController do

  # This should return the minimal set of attributes required to create a valid
  # SupplementPlan. As you add validations to SupplementPlan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupplementPlansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all supplement_plans as @supplement_plans" do
      supplement_plan = SupplementPlan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:supplement_plans).should eq([supplement_plan])
    end
  end

  describe "GET show" do
    it "assigns the requested supplement_plan as @supplement_plan" do
      supplement_plan = SupplementPlan.create! valid_attributes
      get :show, {:id => supplement_plan.to_param}, valid_session
      assigns(:supplement_plan).should eq(supplement_plan)
    end
  end

  describe "GET new" do
    it "assigns a new supplement_plan as @supplement_plan" do
      get :new, {}, valid_session
      assigns(:supplement_plan).should be_a_new(SupplementPlan)
    end
  end

  describe "GET edit" do
    it "assigns the requested supplement_plan as @supplement_plan" do
      supplement_plan = SupplementPlan.create! valid_attributes
      get :edit, {:id => supplement_plan.to_param}, valid_session
      assigns(:supplement_plan).should eq(supplement_plan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SupplementPlan" do
        expect {
          post :create, {:supplement_plan => valid_attributes}, valid_session
        }.to change(SupplementPlan, :count).by(1)
      end

      it "assigns a newly created supplement_plan as @supplement_plan" do
        post :create, {:supplement_plan => valid_attributes}, valid_session
        assigns(:supplement_plan).should be_a(SupplementPlan)
        assigns(:supplement_plan).should be_persisted
      end

      it "redirects to the created supplement_plan" do
        post :create, {:supplement_plan => valid_attributes}, valid_session
        response.should redirect_to(SupplementPlan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supplement_plan as @supplement_plan" do
        # Trigger the behavior that occurs when invalid params are submitted
        SupplementPlan.any_instance.stub(:save).and_return(false)
        post :create, {:supplement_plan => { "user_id" => "invalid value" }}, valid_session
        assigns(:supplement_plan).should be_a_new(SupplementPlan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SupplementPlan.any_instance.stub(:save).and_return(false)
        post :create, {:supplement_plan => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested supplement_plan" do
        supplement_plan = SupplementPlan.create! valid_attributes
        # Assuming there are no other supplement_plans in the database, this
        # specifies that the SupplementPlan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SupplementPlan.any_instance.should_receive(:update_attributes).with({ "user_id" => "" })
        put :update, {:id => supplement_plan.to_param, :supplement_plan => { "user_id" => "" }}, valid_session
      end

      it "assigns the requested supplement_plan as @supplement_plan" do
        supplement_plan = SupplementPlan.create! valid_attributes
        put :update, {:id => supplement_plan.to_param, :supplement_plan => valid_attributes}, valid_session
        assigns(:supplement_plan).should eq(supplement_plan)
      end

      it "redirects to the supplement_plan" do
        supplement_plan = SupplementPlan.create! valid_attributes
        put :update, {:id => supplement_plan.to_param, :supplement_plan => valid_attributes}, valid_session
        response.should redirect_to(supplement_plan)
      end
    end

    describe "with invalid params" do
      it "assigns the supplement_plan as @supplement_plan" do
        supplement_plan = SupplementPlan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SupplementPlan.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplement_plan.to_param, :supplement_plan => { "user_id" => "invalid value" }}, valid_session
        assigns(:supplement_plan).should eq(supplement_plan)
      end

      it "re-renders the 'edit' template" do
        supplement_plan = SupplementPlan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SupplementPlan.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplement_plan.to_param, :supplement_plan => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supplement_plan" do
      supplement_plan = SupplementPlan.create! valid_attributes
      expect {
        delete :destroy, {:id => supplement_plan.to_param}, valid_session
      }.to change(SupplementPlan, :count).by(-1)
    end

    it "redirects to the supplement_plans list" do
      supplement_plan = SupplementPlan.create! valid_attributes
      delete :destroy, {:id => supplement_plan.to_param}, valid_session
      response.should redirect_to(supplement_plans_url)
    end
  end

end
